### ISSUE TITLE
[question] Why 2 of 3?

### ISSUE THREAD

**Issue by sahilc0** [btcguide/btcguide.github.io#14]
Hey @mflaxman - thanks for the guide. 
I'm concerned about the probability of simultaneously losing 2 out of three keys in between "health checks". For that reason I think 3 of 5 might be better. 

Is that fair or do you disagree with the probability of that happening?

**Comment by mflaxman** [comment]
Is [this section](https://btcguide.github.io/quorum-advanced) not clear?

![Screen Shot 2020-09-22 at 10 45 10 AM](https://user-images.githubusercontent.com/448644/93905583-bd6a4480-fcc0-11ea-8b02-a4d4432caf2a.png)

Very open to changes, but closing this github issue for now as it seems there is already a page on this during the setup process.
