### ISSUE TITLE
Publish seed words PDFs without index info

### ISSUE THREAD

**Issue by mflaxman** [btcguide/btcguide.github.io#2]
[The current version](https://btcguide.github.io/setup-wallets/paper) has index #s that take up a lot of space.

**Comment by flyingfaders** [comment]
I've made a new version of the seed words without the indexes and tried to keep it cleaner so I could cut it faster with a paper cutter. I've only tested the printout on one printer, so might need to check it prints ok on other types as the content can fall outside of the bleed / safety zones. 

[BTC_Guide_BIP39_EnglishWords_2020_11_03.pdf](https://github.com/btcguide/btcguide.github.io/files/5478377/BTC_Guide_BIP39_EnglishWords_2020_11_03.pdf)

**Comment by mflaxman** [comment]
Thanks @flyingfaders! I was hoping it would be possible to fit on 1 page, but I think that wasn't realistic :(

This is much better and I think as good as it gets.

Do you want any attribution? The previous version said it was from Cold Code.

**Comment by flyingfaders** [comment]
No attribution needed, this guide and the tools you've made are awesome! Happy to help. Yeah it's too small on an A4 size to get all the words on one page unfortunately. I could make up an A3 version but I feel like not many people would have access to a printer that can print A3 or would be bothered going somewhere to print on that size. 

You can print it double-sided and then just randomly flip the piece you picked out of the hat I suppose? Not sure if that's a good idea for the randomness though...
