### ISSUE TITLE
verify recieve address - watch-only wallets & CLI

### ISSUE THREAD

**Issue by JayOceans** [btcguide/btcguide.github.io#33]
just wanted to let u know ~

i could verify multiple receive addresses
on Electrum & Sentinel (on android)
as "watch-only" wallets 

just copied xpub's from Specter wallets 
& pasted... very easy...

& both formats worked OK
- nested (ypub123...)
- segwit (zpub123...)

Also,
this article helped me do the same, via the CLI

https://coldbit.com/how-to-use-a-trezor-without-leaking-your-balance-and-transaction-history-to-third-parties/

bitcoin-cli deriveaddresses "pkh(xpub6D8yQnAtMgSb5biQTYrwzEvhodb1CHsZnvgecPWc8zykuPM61CueevG4EbWjurYstEEvaC2nX3b74od5khrEMqz5unVprSf2dSQHpcX2Ts5/0/*)#kkz0hv84" "[0,2]"

"1PyzQnq125CAsnUsbeXsq2H8STfRutJyJj",
  "1HNSjatqJcWNiBLU23uWijAwPQEnMFjCE",
  "15eKaDXtE1ghsixJoznA1edgZ2UrsB6f3x"

**Comment by mflaxman** [comment]
My guide is explicitly for processes that don't require use of the command-line and are possible for non-experts, with the goal of eventually eliminating even advanced steps. Electrum with multisig is unfortunately far too hard. This feature could make using it for verifying a receive address manageable:
https://github.com/cryptoadvance/specter-desktop/issues/212#issuecomment-699587232

That article is good, it's the one linked to on the Trezor page:
https://btcguide.github.io/known-issues/hardware/trezor
