### ISSUE TITLE
Confused for the "Seeds" part

### ISSUE THREAD

**Issue by BitcoinLixin** [btcguide/btcguide.github.io#43]
https://btcguide.github.io/backup-wallet/

"These are your 24 word BIP39 phrases. You only need to have m (of your total n) seeds to recover your funds."

Here you want to say - you need m of n seed to sign a transaction, right?

"recover your funds" feels confusing to me, it could refer to 1) sign a transaction or 2) recover your wallet.

**Comment by mflaxman** [comment]
Thanks. Look good now?
