### ISSUE TITLE
Confusing heading vs the body of the paragraph - m greater than 5

### ISSUE THREAD

**Issue by wrengulf** [btcguide/btcguide.github.io#49]
On this page https://btcguide.github.io/quorum-advanced

Shouldn't the heading at the bottom read "M>5: Nonstandard transactions"  rather than "N>5: Nonstandard transactions" ?

**Comment by mflaxman** [comment]
I think my info here is very outdated, do you have a source on the current standard sizes?

https://twitter.com/mflaxman/status/1339718993456852993

**Comment by wrengulf** [comment]
I don't sorry. I'd like to help out with this guide (I rely on it a lot and think it's fantastic), maybe you could tag some "good first issues" ? Or is there any particular area you'd like the guide to improve in ? Maybe screenshots ? Or adding explanations on Advanced to dos ?
