### ISSUE TITLE
Evaluate whether Blockstream Jade should be recommended

### ISSUE THREAD

**Issue by robot-dreams** [btcguide/btcguide.github.io#56]
Currently the only recommended hardware wallets are Coldcard and Cobo Vault. If the new [Blockstream Jade](https://store.blockstream.com/product/blockstream-jade/) can also be recommended, it would be a significant step towards a "canonical" 3-of-5 setup.

**Comment by mflaxman** [comment]
I heard it doesn't yet support multisig, but haven't researched. But would love to try it out if/when it does!

**Comment by robot-dreams** [comment]
Makes sense! From https://bitcointalk.org/index.php?topic=5306988.0 it looks like the Jade doesn't have the needed support yet (but might in the future):

> Q: Is Jade PSBT compatible?
> A: Jade uses wally which has PSBT support. At the moment Jade supports Green multisig which doesn't take advantage of PSBT yet. We plan to add to Jade single sig and PSBT support.

This can be re-opened once the Jade supports multisig.
