### ISSUE TITLE
Some instructions confusing. Need for updated flow?

### ISSUE THREAD

**Issue by merland** [btcguide/btcguide.github.io#7]
`In the previous step, you saved your extended public key information (something like [083AA3DB/48'/0'/0'/2']Zpub75b...bhK) to a DVD-R or USB pen-drive.`
(https://btcguide.github.io/setup-wallets/paper)

Could be just a matter of WIP, but could you clarify a bit here? 
The "previous step" in this context is using SeedPicker to get the full seed phrase only. And only on paper and not on DVD or pendrive. Also, the heading talks about QR-code/webcam but the text does not. 

Before working too much with this text, however: Maybe SeedPicker should be updated to display a QR code with all that info? (fingerprint, derivationpath, Zpub). Could make the flow simpler? May need two computers though, or a printout of the QR-code. Thoughts?

**Comment by mflaxman** [comment]
Oops, that was old copy from when it was using https://github.com/mflaxman/human-rng-electrum. Def needs updating.

A QR code would be awesome! Maybe the easiest for v1 would be a simple file download of a `.json` file to upload to Specter? Will add a github issue to seedpicker now.

**Comment by mflaxman** [comment]
@merland I just updated the paper wallet generation instructions:
https://github.com/btcguide/btcguide.github.io/commit/7ce6d897b1212840960b154bd1b524743aab3c93

Major changes:
* Incorporates the new `seedpickerxp-foo.json` file + screenshots.
* Responds to some of your feedback (like QR code)
* Updates links to my new CLI seedpicker golang tool (feedback welcome, very rough!): https://github.com/mflaxman/human-rng-golang

I think this is still pretty rough as 1) it's still complicated and 2) I figured you might want to change the UI on seedpicker a bit as it migrates to being a Specter-Desktop tool (not an electrum one). For example, the minimum/required/basic info to use Specter-Desktop includes the root fingerprint and derivation path, but this is buried under `Show more (for advanced users)`.

Do you want to take a look at the current instructions and see what changes might make sense to this guide (and perhaps seedpicker copy?):
https://btcguide.github.io/setup-wallets/paper

As always, PRs very welcome :)

**Comment by merland** [comment]
Nicely done! 
I think the greatest favor I can do to the guide right now is to simplify/change the SeedPicker GUI so I will focus on that. 

A nice long term goal would be to make SeedPicker a more general tool, not specific to only Specter, but it's of course better to start narrow and add more later, when we have had the chance to add and verify more wallets.

**Comment by mflaxman** [comment]
Sounds good! I'm closing this issue for now, I want to keep the GH issues focused on specific/actionable things.

As you make changes to SeedPicker feel free to reopen with anything you have in mind.

I agree re other tools, but it might be a while before there is a viable second option. Electrum is hard to use even for experts and has limited BIP39 support (and is threatening to drop it, which I think is insane).
