### ISSUE TITLE
BlueWallet Multisig Option?

### ISSUE THREAD

**Issue by blankscreengithub** [btcguide/btcguide.github.io#87]
BlueWallet for Android/iOS/macOS has the ability to create multisig wallets using hardware devices. Could this option be expanded on in Setup Computer/App somewhere?

**Comment by mflaxman** [comment]
IIRC it only works when connected to the internet (won't work in airplane mode) and doesn't support testnet?

I'd be open to it (with appropriate disclaimers about the danger of mobile) if it could work offline and on testnet.

**Comment by blankscreengithub** [comment]
Yeah, testnet I don't think is an option, but I don't know why internet connectivity is an issue. Something has to broadcast the transaction and BlueWallet would broadcast the transaction just like Specter would broadcast the transaction.

You don't have to keep any keys with BlueWallet as all the keys can be in hardware wallets. BlueWallet also has a macOS version just like Specter so it doesn't have to be a mobile device.

**Comment by mflaxman** [comment]
For coordinator it could work (with obvious warnings about how bad it is for your privacy), but I meant as a consigner it needs those basic things.

Specter-Desktop has 10x as many eyeballs and is full featured, I see no reason to recommend bluewallet as coordinator for now.

**Comment by mflaxman** [comment]
UPDATE: Bluewallet claims they support offline usage. With testnet support, it'd be worth checking out.

https://twitter.com/bluewalletio/status/1359255767849836549
