### ISSUE TITLE
Specter seems to support bitbox02 now

### ISSUE THREAD

**Issue by donnlee** [btcguide/btcguide.github.io#88]
I've been researching the bitbox02 wallet.

`_pages/known-issues/hardware/bitbox.md` might have old info that Specter doesn't support it.

https://github.com/cryptoadvance/specter-desktop says Specter supports bitbox02.

Any chance you'll look into bitbox02 as another candidate in a quorum?  It claims to have multisig support against specific attacks mentioned in your interview with Stephan. 
https://benma.github.io/2020/11/05/multisig-xpubs-verification.html
Though, it seems to require (or suggest) Electrum as the user-facing software.

**Comment by mflaxman** [comment]
BB02 doesn't support multisig with Specter-Desktop yet. I would be very interested if that changed.

https://twitter.com/_benma_/status/1359172368103575557?s=21
